name: dart_varuint_bitcoin
description: This package uses it to encode/decode the number as bitcoin variable length integer.
version: 1.0.2
repository: https://github.com/dart-bitcoin-lib/dart-varuint-bitcoin
homepage: https://github.com/dart-bitcoin-lib/dart-varuint-bitcoin

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  convert: ^3.0.1
  lints: ^1.0.0
  test: ^1.16.0
